### ISSUE TITLE
앱 처음 실행시 뜨는 화면 구성

### ISSUE THREAD

**Issue by Junho-Seo-0304** [Nexters/water-android#11]
- 어플 설명하는 화면

- 닉네임 등록하는 화면

- 키와 몸무게 입력하는 화면

- 자주 마시는 음료 등록하는 화면

**Comment by hyunss** [comment]
- [ ] 어플 설명하는 화면

- [ ] 닉네임 등록하는 화면

- [ ] 키와 몸무게 입력하는 화면

- [ ] 자주 마시는 음료 등록하는 화면 (intro에서 구현 x)
