### ISSUE TITLE
intro 수정 사항

### ISSUE THREAD

**Issue by Junho-Seo-0304** [Nexters/water-android#37]
- 뒤로 가기 누르면 activity 종료가 아닌 전 fragment로 가기
- 입력 값 없을 시 버튼 안눌리기

**Comment by hyunss** [comment]
뒤로 가기 버튼 tab 시 이전 fragment로 이동 구현 완료

**Comment by hyunss** [comment]
name & weight & height 버튼 clickable 구현 완료
